name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: node20
    
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.2
      with:
        # Set always-auth in npmrc.
        always-auth: npmrc
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 12.x, 10.15.1, >=10.15.0
        # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
        node-version-file: package.json, .nvmrc, .node-version, .tool-versions
        # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
        architecture: x86, x64
          
    - name: Add conda to system path
      run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
          conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
          conda install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
          pytest
